# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RpcEnvelope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RpcEnum_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RpcEnvelope.proto',
  package='',
  serialized_pb=_b('\n\x11RpcEnvelope.proto\x1a\rRpcEnum.proto\"\xd8\x04\n\x07Request\x12(\n\tdirection\x18\x01 \x02(\x0e\x32\x15.RpcEnum.RpcDirection\x12\x0e\n\x06rpc_id\x18\x03 \x01(\x03\x12#\n\x08requests\x18\x04 \x03(\x0b\x32\x11.Request.Requests\x12#\n\x08unknown6\x18\x06 \x01(\x0b\x32\x11.Request.Unknown6\x12\x10\n\x08latitude\x18\x07 \x01(\x06\x12\x11\n\tlongitude\x18\x08 \x01(\x06\x12\x10\n\x08\x61ltitude\x18\t \x01(\x06\x12\x1f\n\x04\x61uth\x18\n \x01(\x0b\x32\x11.Request.AuthInfo\x12 \n\x0b\x61uth_ticket\x18\x0b \x01(\x0b\x32\x0b.AuthTicket\x12\x11\n\tunknown12\x18\x0c \x01(\x03\x1a\x44\n\x08Requests\x12$\n\x04type\x18\x01 \x02(\x0e\x32\x16.RpcEnum.RequestMethod\x12\x12\n\nparameters\x18\x02 \x01(\x0c\x1an\n\x08\x41uthInfo\x12\x10\n\x08provider\x18\x01 \x02(\t\x12$\n\x05token\x18\x02 \x02(\x0b\x32\x15.Request.AuthInfo.JWT\x1a*\n\x03JWT\x12\x10\n\x08\x63ontents\x18\x01 \x02(\t\x12\x11\n\tunknown13\x18\x02 \x02(\x05\x1a\x1c\n\x08Unknown3\x12\x10\n\x08unknown4\x18\x01 \x02(\t\x1ah\n\x08Unknown6\x12\x10\n\x08unknown1\x18\x01 \x02(\x05\x12,\n\x08unknown2\x18\x02 \x02(\x0b\x32\x1a.Request.Unknown6.Unknown2\x1a\x1c\n\x08Unknown2\x12\x10\n\x08unknown1\x18\x01 \x02(\x0c\"\xe2\x02\n\x08Response\x12(\n\tdirection\x18\x01 \x02(\x0e\x32\x15.RpcEnum.RpcDirection\x12\x10\n\x08unknown2\x18\x02 \x01(\x03\x12\x0f\n\x07\x61pi_url\x18\x03 \x01(\t\x12$\n\x08unknown6\x18\x06 \x02(\x0b\x32\x12.Response.Unknown6\x12 \n\x0b\x61uth_ticket\x18\x07 \x01(\x0b\x32\x0b.AuthTicket\x12\x11\n\tresponses\x18\x64 \x03(\x0c\x1ai\n\x08Unknown6\x12\x10\n\x08unknown1\x18\x01 \x02(\x05\x12-\n\x08unknown2\x18\x02 \x02(\x0b\x32\x1b.Response.Unknown6.Unknown2\x1a\x1c\n\x08Unknown2\x12\x10\n\x08unknown1\x18\x01 \x02(\x0c\x1a\x43\n\x08Unknown7\x12\x11\n\tunknown71\x18\x01 \x01(\x0c\x12\x11\n\tunknown72\x18\x02 \x01(\x03\x12\x11\n\tunknown73\x18\x03 \x01(\x0c\"E\n\nAuthTicket\x12\r\n\x05start\x18\x01 \x01(\x0c\x12\x1b\n\x13\x65xpire_timestamp_ms\x18\x02 \x01(\x04\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x0c')
  ,
  dependencies=[RpcEnum_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUEST_REQUESTS = _descriptor.Descriptor(
  name='Requests',
  full_name='Request.Requests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Request.Requests.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='Request.Requests.parameters', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=389,
)

_REQUEST_AUTHINFO_JWT = _descriptor.Descriptor(
  name='JWT',
  full_name='Request.AuthInfo.JWT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contents', full_name='Request.AuthInfo.JWT.contents', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown13', full_name='Request.AuthInfo.JWT.unknown13', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=501,
)

_REQUEST_AUTHINFO = _descriptor.Descriptor(
  name='AuthInfo',
  full_name='Request.AuthInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='provider', full_name='Request.AuthInfo.provider', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='Request.AuthInfo.token', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_AUTHINFO_JWT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=501,
)

_REQUEST_UNKNOWN3 = _descriptor.Descriptor(
  name='Unknown3',
  full_name='Request.Unknown3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown4', full_name='Request.Unknown3.unknown4', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=531,
)

_REQUEST_UNKNOWN6_UNKNOWN2 = _descriptor.Descriptor(
  name='Unknown2',
  full_name='Request.Unknown6.Unknown2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='Request.Unknown6.Unknown2.unknown1', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=637,
)

_REQUEST_UNKNOWN6 = _descriptor.Descriptor(
  name='Unknown6',
  full_name='Request.Unknown6',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='Request.Unknown6.unknown1', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown2', full_name='Request.Unknown6.unknown2', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_UNKNOWN6_UNKNOWN2, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=637,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='Request.direction', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpc_id', full_name='Request.rpc_id', index=1,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requests', full_name='Request.requests', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown6', full_name='Request.unknown6', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Request.latitude', index=4,
      number=7, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Request.longitude', index=5,
      number=8, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='Request.altitude', index=6,
      number=9, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth', full_name='Request.auth', index=7,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth_ticket', full_name='Request.auth_ticket', index=8,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown12', full_name='Request.unknown12', index=9,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_REQUESTS, _REQUEST_AUTHINFO, _REQUEST_UNKNOWN3, _REQUEST_UNKNOWN6, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=637,
)


_RESPONSE_UNKNOWN6_UNKNOWN2 = _descriptor.Descriptor(
  name='Unknown2',
  full_name='Response.Unknown6.Unknown2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='Response.Unknown6.Unknown2.unknown1', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=637,
)

_RESPONSE_UNKNOWN6 = _descriptor.Descriptor(
  name='Unknown6',
  full_name='Response.Unknown6',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='Response.Unknown6.unknown1', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown2', full_name='Response.Unknown6.unknown2', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_UNKNOWN6_UNKNOWN2, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=820,
  serialized_end=925,
)

_RESPONSE_UNKNOWN7 = _descriptor.Descriptor(
  name='Unknown7',
  full_name='Response.Unknown7',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown71', full_name='Response.Unknown7.unknown71', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown72', full_name='Response.Unknown7.unknown72', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown73', full_name='Response.Unknown7.unknown73', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=927,
  serialized_end=994,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='Response.direction', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown2', full_name='Response.unknown2', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='api_url', full_name='Response.api_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown6', full_name='Response.unknown6', index=3,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth_ticket', full_name='Response.auth_ticket', index=4,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responses', full_name='Response.responses', index=5,
      number=100, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_UNKNOWN6, _RESPONSE_UNKNOWN7, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=640,
  serialized_end=994,
)


_AUTHTICKET = _descriptor.Descriptor(
  name='AuthTicket',
  full_name='AuthTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='AuthTicket.start', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expire_timestamp_ms', full_name='AuthTicket.expire_timestamp_ms', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='AuthTicket.end', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=996,
  serialized_end=1065,
)

_REQUEST_REQUESTS.fields_by_name['type'].enum_type = RpcEnum_pb2._REQUESTMETHOD
_REQUEST_REQUESTS.containing_type = _REQUEST
_REQUEST_AUTHINFO_JWT.containing_type = _REQUEST_AUTHINFO
_REQUEST_AUTHINFO.fields_by_name['token'].message_type = _REQUEST_AUTHINFO_JWT
_REQUEST_AUTHINFO.containing_type = _REQUEST
_REQUEST_UNKNOWN3.containing_type = _REQUEST
_REQUEST_UNKNOWN6_UNKNOWN2.containing_type = _REQUEST_UNKNOWN6
_REQUEST_UNKNOWN6.fields_by_name['unknown2'].message_type = _REQUEST_UNKNOWN6_UNKNOWN2
_REQUEST_UNKNOWN6.containing_type = _REQUEST
_REQUEST.fields_by_name['direction'].enum_type = RpcEnum_pb2._RPCDIRECTION
_REQUEST.fields_by_name['requests'].message_type = _REQUEST_REQUESTS
_REQUEST.fields_by_name['unknown6'].message_type = _REQUEST_UNKNOWN6
_REQUEST.fields_by_name['auth'].message_type = _REQUEST_AUTHINFO
_REQUEST.fields_by_name['auth_ticket'].message_type = _AUTHTICKET
_RESPONSE_UNKNOWN6_UNKNOWN2.containing_type = _RESPONSE_UNKNOWN6
_RESPONSE_UNKNOWN6.fields_by_name['unknown2'].message_type = _RESPONSE_UNKNOWN6_UNKNOWN2
_RESPONSE_UNKNOWN6.containing_type = _RESPONSE
_RESPONSE_UNKNOWN7.containing_type = _RESPONSE
_RESPONSE.fields_by_name['direction'].enum_type = RpcEnum_pb2._RPCDIRECTION
_RESPONSE.fields_by_name['unknown6'].message_type = _RESPONSE_UNKNOWN6
_RESPONSE.fields_by_name['auth_ticket'].message_type = _AUTHTICKET
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['AuthTicket'] = _AUTHTICKET

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(

  Requests = _reflection.GeneratedProtocolMessageType('Requests', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST_REQUESTS,
    __module__ = 'RpcEnvelope_pb2'
    # @@protoc_insertion_point(class_scope:Request.Requests)
    ))
  ,

  AuthInfo = _reflection.GeneratedProtocolMessageType('AuthInfo', (_message.Message,), dict(

    JWT = _reflection.GeneratedProtocolMessageType('JWT', (_message.Message,), dict(
      DESCRIPTOR = _REQUEST_AUTHINFO_JWT,
      __module__ = 'RpcEnvelope_pb2'
      # @@protoc_insertion_point(class_scope:Request.AuthInfo.JWT)
      ))
    ,
    DESCRIPTOR = _REQUEST_AUTHINFO,
    __module__ = 'RpcEnvelope_pb2'
    # @@protoc_insertion_point(class_scope:Request.AuthInfo)
    ))
  ,

  Unknown3 = _reflection.GeneratedProtocolMessageType('Unknown3', (_message.Message,), dict(
    DESCRIPTOR = _REQUEST_UNKNOWN3,
    __module__ = 'RpcEnvelope_pb2'
    # @@protoc_insertion_point(class_scope:Request.Unknown3)
    ))
  ,

  Unknown6 = _reflection.GeneratedProtocolMessageType('Unknown6', (_message.Message,), dict(

    Unknown2 = _reflection.GeneratedProtocolMessageType('Unknown2', (_message.Message,), dict(
      DESCRIPTOR = _REQUEST_UNKNOWN6_UNKNOWN2,
      __module__ = 'RpcEnvelope_pb2'
      # @@protoc_insertion_point(class_scope:Request.Unknown6.Unknown2)
      ))
    ,
    DESCRIPTOR = _REQUEST_UNKNOWN6,
    __module__ = 'RpcEnvelope_pb2'
    # @@protoc_insertion_point(class_scope:Request.Unknown6)
    ))
  ,
  DESCRIPTOR = _REQUEST,
  __module__ = 'RpcEnvelope_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.Requests)
_sym_db.RegisterMessage(Request.AuthInfo)
_sym_db.RegisterMessage(Request.AuthInfo.JWT)
_sym_db.RegisterMessage(Request.Unknown3)
_sym_db.RegisterMessage(Request.Unknown6)
_sym_db.RegisterMessage(Request.Unknown6.Unknown2)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(

  Unknown6 = _reflection.GeneratedProtocolMessageType('Unknown6', (_message.Message,), dict(

    Unknown2 = _reflection.GeneratedProtocolMessageType('Unknown2', (_message.Message,), dict(
      DESCRIPTOR = _RESPONSE_UNKNOWN6_UNKNOWN2,
      __module__ = 'RpcEnvelope_pb2'
      # @@protoc_insertion_point(class_scope:Response.Unknown6.Unknown2)
      ))
    ,
    DESCRIPTOR = _RESPONSE_UNKNOWN6,
    __module__ = 'RpcEnvelope_pb2'
    # @@protoc_insertion_point(class_scope:Response.Unknown6)
    ))
  ,

  Unknown7 = _reflection.GeneratedProtocolMessageType('Unknown7', (_message.Message,), dict(
    DESCRIPTOR = _RESPONSE_UNKNOWN7,
    __module__ = 'RpcEnvelope_pb2'
    # @@protoc_insertion_point(class_scope:Response.Unknown7)
    ))
  ,
  DESCRIPTOR = _RESPONSE,
  __module__ = 'RpcEnvelope_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.Unknown6)
_sym_db.RegisterMessage(Response.Unknown6.Unknown2)
_sym_db.RegisterMessage(Response.Unknown7)

AuthTicket = _reflection.GeneratedProtocolMessageType('AuthTicket', (_message.Message,), dict(
  DESCRIPTOR = _AUTHTICKET,
  __module__ = 'RpcEnvelope_pb2'
  # @@protoc_insertion_point(class_scope:AuthTicket)
  ))
_sym_db.RegisterMessage(AuthTicket)


# @@protoc_insertion_point(module_scope)
